In [3]:
import numpy as np;
list=[1,2,3]
np.array(list)




array([1, 2, 3])

In [4]:
list2=[[1,2,3,4],[5,6,7,8]]
np.array(list2)


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [5]:
np.arange(0,10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.zeros(2)



array([0., 0.])

In [7]:
np.zeros((3,3))



array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.ones(3)


array([1., 1., 1.])

In [10]:
np.eye(2)


array([[1., 0.],
       [0., 1.]])

In [11]:
np.linspace(0,11,3)

array([ 0. ,  5.5, 11. ])

In [12]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [13]:
np.random.rand(20)


array([0.93540783, 0.15205992, 0.76902159, 0.5711081 , 0.53575256,
       0.13227883, 0.97806562, 0.01851633, 0.83953798, 0.82903806,
       0.94306563, 0.76569694, 0.72013826, 0.4381558 , 0.04828666,
       0.21051804, 0.37383366, 0.68822626, 0.08243725, 0.20395188])

In [14]:
np.random.rand(5,5)

array([[0.80642281, 0.69938577, 0.12604049, 0.3505418 , 0.21079014],
       [0.51630374, 0.7696046 , 0.82601557, 0.25095222, 0.84669055],
       [0.93638312, 0.29017819, 0.18520364, 0.85611673, 0.90207245],
       [0.45903829, 0.33489922, 0.44134154, 0.37098934, 0.08811261],
       [0.79534037, 0.69520007, 0.22677412, 0.93776039, 0.60127545]])

In [15]:
np.random.randn(7,5)


array([[ 1.53336443e-01,  1.00456848e+00, -1.30560825e-01,
        -1.16612682e+00,  9.71321344e-02],
       [-4.37088878e-01,  1.42382331e+00,  3.82277964e-01,
        -2.23706364e+00, -2.94996484e-01],
       [ 1.10292880e+00, -1.82443459e+00,  2.51302271e+00,
         9.32498078e-01, -1.32297912e+00],
       [-4.17853561e-01, -1.63399595e-01, -1.44143385e+00,
        -1.64010196e+00,  1.64849398e+00],
       [-1.32096908e-01,  6.55270914e-03, -5.82259714e-01,
         4.08987950e-01, -6.56521407e-01],
       [ 5.47276477e-02,  1.55289713e-01, -8.41780247e-01,
        -7.67279191e-01, -1.72437392e-01],
       [-2.31245989e+00, -2.25167977e-05, -3.26686374e-01,
        -1.34572157e+00,  2.95500770e-03]])

In [16]:
np.random.randint(1,100)

21

In [17]:
np.arange(1,25)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [18]:
np.random.randint(1,100,11)

array([14, 58,  8,  7, 70, 72, 88, 39, 91, 24, 10])

In [19]:

a=np.random.rand(20)
a.reshape(5,4)

array([[0.05213426, 0.18008541, 0.98389779, 0.29087093],
       [0.79322849, 0.02986413, 0.13920057, 0.11027116],
       [0.60373108, 0.7220233 , 0.66438819, 0.13055456],
       [0.74983484, 0.66470627, 0.13049508, 0.88158771],
       [0.80225786, 0.20783111, 0.22030168, 0.47041063]])

In [20]:
a.max()

0.9838977855182353

In [22]:
a.min()

0.02986413364519014

In [23]:
a.shape

(20,)

In [24]:
a.argmax()

2

In [25]:
a.argmin()

5

In [26]:
a.reshape(20,1).shape

(20, 1)

In [27]:
a.reshape(20,1)

array([[0.05213426],
       [0.18008541],
       [0.98389779],
       [0.29087093],
       [0.79322849],
       [0.02986413],
       [0.13920057],
       [0.11027116],
       [0.60373108],
       [0.7220233 ],
       [0.66438819],
       [0.13055456],
       [0.74983484],
       [0.66470627],
       [0.13049508],
       [0.88158771],
       [0.80225786],
       [0.20783111],
       [0.22030168],
       [0.47041063]])

In [28]:
a.dtype

dtype('float64')

In [29]:
a[3]

0.29087092788184865

In [31]:
arr=np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [33]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [34]:
arr[0:5]=100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])