In [ ]:
import numpy as np;
m=np.arange(0,10)
m+m

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
import numpy as np;
m=np.arange(0,10)
m-m

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
import numpy as np;
m=np.arange(0,10)
m*m

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
import numpy as np;
m=np.arange(0,10)
m/m

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [ ]:
import numpy as np;
m=np.arange(0,10)
2*m

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])